"""v1.2-v2.0 orders redemption oauth audit

Revision ID: 7481b278d83f
Revises: 876124e74d42
Create Date: 2026-07-03 09:39:28.168466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7481b278d83f'
down_revision: Union[str, Sequence[str], None] = '876124e74d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('sub', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_accounts_sub'), ['sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('redemption_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('amount_credits', sa.BigInteger(), nullable=False),
    sa.Column('batch', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redemption_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redemption_codes_code'), ['code'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_no', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('pay_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pay_address', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('extra', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.drop_column('expires_at')
        batch_op.drop_column('extra')
        batch_op.drop_column('pay_address')
        batch_op.drop_column('pay_url')
        batch_op.drop_column('order_no')

    with op.batch_alter_table('redemption_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redemption_codes_code'))

    op.drop_table('redemption_codes')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_sub'))
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_provider'))

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
