"""init schema

Revision ID: 876124e74d42
Revises: 
Create Date: 2026-07-02 23:11:20.937485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876124e74d42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('ref', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_ledger_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_keys', sa.Text(), nullable=False),
    sa.Column('models', sa.Text(), nullable=False),
    sa.Column('model_map', sa.Text(), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('input_price', sa.BigInteger(), nullable=False),
    sa.Column('output_price', sa.BigInteger(), nullable=False),
    sa.Column('cache_price', sa.BigInteger(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_pricing_model'), ['model'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_credits', sa.BigInteger(), nullable=False),
    sa.Column('amount_money', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_order', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('quota_tokens', sa.BigInteger(), nullable=True),
    sa.Column('used_tokens', sa.BigInteger(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('allowed_models', sa.Text(), nullable=True),
    sa.Column('allowed_groups', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('token_name', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('upstream_model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('stream', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('frozen', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_ts'))

    op.drop_table('usage_logs')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_key'))

    op.drop_table('tokens')
    op.drop_table('settings')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))

    op.drop_table('orders')
    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_pricing_model'))

    op.drop_table('model_pricing')
    op.drop_table('channels')
    with op.batch_alter_table('billing_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_billing_ledger_ts'))

    op.drop_table('billing_ledger')
    # ### end Alembic commands ###
